#----------------------------------
# This is my test Workflow
#
# By Niko 2021.
#----------------------------------

name: my-github-actions-test

# Controls when the action will run. 
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "hello World from testing job"

  my_deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message2
      run: echo "Hello World from deployment job"
        
    
        
